WifiTrackerLib: Set min_sdk_version to 29.
* Required to fix a compatibility issue with our
  OTA app which depends on SettingsLib to use layout
  components from fw/b.

/out/soong/.intermediates/frameworks/base/packages/SettingsLib/SettingsLib/android_common/manifest_fixer/AndroidManifest.xml:19:5-73
Error: uses-sdk:minSdkVersion 29 cannot be smaller than version 31 declared in library /out/soong/.intermediates/frameworks/opt/net/wifi/libs/WifiT
rackerLib/WifiTrackerLib/android_common/manifest_fixer/AndroidManifest.xml as the library might be using APIs not available in 29
	Suggestion: use a compatible library with a minSdk of at most 29,
		or increase this project's minSdk version to at least 31,
		or use tools:overrideLibrary="com.android.wifitrackerlib" to force usage (may lead to runtime failures)

Signed-off-by: spezi77 <spezi7713@gmx.net>
Change-Id: I39f5026a291953bb9c09a94b5b718e956fb3575e
Signed-off-by: Wrdn28 <ifloraxd@gmail.com>